# development:
#   host: dev.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
# staging:
#   host: staging.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
#production:
#  host: https://station.locomotive.works
#  handle: limitless-pebble-2744
#  email: justin@6bitconsulting.com
#  api_key: 262cd9f4270f0953746228346efeb43a911cb18f
production:
  host: https://station.locomotive.works
  handle: natural-darkness-4055
  email: aaroncontreras1990@gmail.com
  api_key: 07e7f0778392499f31d51bebcc6a467d42ac57b6